#define INT 			1
#define FLOAT   		2
#define	DOUBLE  		3
#define	CHAR 			4
#define	VOID 			5	
#define	STRUCT 			6
#define	IF  			7
#define	ELSE   			8
#define WHILE  			9
#define DO  			10
#define RETURN          11 
#define	SWITCH  		12
#define	BREAK  			13
#define	PRINT  			14
#define	CASE  			15	
#define	DEFAULT  		16		
#define	TRUE  			17		
#define	FALSE  			18	
#define	OR  			19
#define	AND  			20
#define	NOT  			21
#define	LPAR  			22
#define	RPAR  			23
#define	LBRA  			24
#define	RBRA  			25
#define	LCUR  			26
#define	RCUR  			27	
#define	PLUS2  			28
#define	MINUS2  		29		
#define	MUL  			30
#define	DIV  			31
#define	MOD  			32
#define	PLUS  			33
#define	MINUS  			34
#define	LESS  			35	
#define	LESSEQ  		36
#define	MORE  			37
#define	MOREEQ  		38
#define	EQUAL2  		39
#define	NOTQ  			40
#define	EQUAL  			41
#define	SCOLON  		42
#define	COMMA  			43
#define	COLON  			44
#define	INTNUM  		45	
#define	HEXNUM  		46
#define	DECNUM  		47
#define	EXPNUM  		48
#define	ID				49
#define	CONSCHAR  		50
#define	CONSSTRING  	51	